#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
elif [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi

set -x

${PREFIX}pytest --cov-report term-missing --cov-report=xml:coverage.xml --cov=aioworker tests/
${PREFIX}black aioworker tests --check
${PREFIX}flake8 --max-line-length=88 aioworker/ tests/
${PREFIX}mypy aioworker --ignore-missing-imports --no-strict-optional
